# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYFqfQhD3P_6MD6td4-h7lQRTUmtnIFt
"""

import streamlit as st
from PIL import Image

st.set_page_config(page_title="寿司握りアプリ", page_icon="🍣", layout="centered")

st.title("🍣 寿司を握ろう！")

st.write("あなたの好きなネタとシャリの量を選んで、オリジナル寿司を握ってみよう！")

# 寿司ネタの選択
sushi_toppings = [
    "まぐろ", "サーモン", "エビ", "たまご", "イカ", "ほたて", "こはだ", "穴子", "いくら", "うに"
]
selected_topping = st.selectbox("🍣 好きなネタを選んでください", sushi_toppings)

# シャリの量を選ぶ
shari_size = st.slider("🍚 シャリの量（g）", 10, 100, 50)

# ワサビの有無
wasabi = st.radio("🌿 ワサビは？", ["あり", "なし"], horizontal=True)

# 寿司を握るボタン
if st.button("👋 寿司を握る！"):
    st.success(f"{selected_topping}の寿司を握りました！")
    st.write(f"▶ シャリの量: **{shari_size}g**")
    st.write(f"▶ ワサビ: **{wasabi}**")

    # ネタ画像の表示
    sushi_images = {
        "まぐろ": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Maguro_sushi_01.jpg",
        "サーモン": "https://upload.wikimedia.org/wikipedia/commons/6/60/Sake_nigiri.jpg",
        "エビ": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Ebi_sushi_by_matsuyuki.jpg",
        "たまご": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Tamagoyaki_sushi.jpg",
        "イカ": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Ika_sushi.jpg",
        "ほたて": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Hotate_sushi.jpg",
        "こはだ": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Kohada.jpg",
        "穴子": "https://upload.wikimedia.org/wikipedia/commons/4/42/Anago_sushi.jpg",
        "いくら": "https://upload.wikimedia.org/wikipedia/commons/d/de/Ikura_gunkan.jpg",
        "うに": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Uni_gunkan_sushi.jpg"
    }

    image_url = sushi_images.get(selected_topping)
    st.image(image_url, caption=f"{selected_topping}の寿司", use_container_width=True)

else:
    st.info("上の選択をしてから『寿司を握る！』を押してください。")

# 寿司イラスト（全体絵）を表示
st.markdown("---")
st.subheader("🎨 寿司盛り合わせのイラスト")

# フリー寿司イラストの表示（商用利用OKのURL）
sushi_illustration_url = "https://illustimage.com/photo/2187.png"
st.image(sushi_illustration_url, caption="寿司盛り合わせ", use_container_width=True)

st.caption("© 2025 寿司職人シミュレーター by Streamlit")